const fs = require('fs');
const path = require('path');

const base = 'F:/desktop/choco_gui/lib';

// ---- choco_service.dart ----
const chocoService = [
  "import 'dart:convert';",
  "import 'dart:io';",
  "import '../models/package_model.dart';",
  "",
  "/// Result wrapper for Chocolatey command executions.",
  "class ChocoResult {",
  "  final bool success;",
  "  final String output;",
  "  final String error;",
  "  final int exitCode;",
  "",
  "  const ChocoResult({",
  "    required this.success,",
  "    required this.output,",
  "    required this.error,",
  "    required this.exitCode,",
  "  });",
  "}",
  "",
  "/// Service that wraps all Chocolatey CLI commands.",
  "class ChocoService {",
  "  static const String _powershell = 'powershell.exe';",
  "",
  "  /// Returns `true` if the `choco` command is available on PATH.",
  "  Future<bool> isChocoInstalled() async {",
  "    return await getChocoVersion() != null;",
  "  }",
  "",
  "  /// Returns the installed Chocolatey version string, or `null` on error.",
  "  Future<String?> getChocoVersion() async {",
  "    try {",
  "      final result = await Process.run(",
  "        _powershell,",
  "        ['-NoProfile', '-Command', 'choco --version'],",
  "        runInShell: false,",
  "      );",
  "      if (result.exitCode == 0) {",
  "        return (result.stdout as String).trim();",
  "      }",
  "      return null;",
  "    } catch (_) {",
  "      return null;",
  "    }",
  "  }",
  "",
  "  /// Runs the Chocolatey install script in an elevated PowerShell process.",
  "  Future<ChocoResult> installChocolatey({",
  "    void Function(String line)? onOutput,",
  "  }) async {",
  "    const script =",
  "        r'Set-ExecutionPolicy Bypass -Scope Process -Force; '",
  "        r'[System.Net.ServicePointManager]::SecurityProtocol = '",
  "        r'[System.Net.ServicePointManager]::SecurityProtocol -bor 3072; '",
  "        \"iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))\";",
  "",
  "    final outputBuf = StringBuffer();",
  "    final errorBuf = StringBuffer();",
  "",
  "    try {",
  "      final process = await Process.start(",
  "        _powershell,",
  "        ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-Command', script],",
  "        runInShell: false,",
  "      );",
  "      process.stdout",
  "          .transform(const Utf8Decoder(allowMalformed: true))",
  "          .transform(const LineSplitter())",
  "          .listen((line) {",
  "        outputBuf.writeln(line);",
  "        onOutput?.call(line);",
  "      });",
  "      process.stderr",
  "          .transform(const Utf8Decoder(allowMalformed: true))",
  "          .transform(const LineSplitter())",
  "          .listen((line) {",
  "        errorBuf.writeln(line);",
  "        onOutput?.call('[ERR] $line');",
  "      });",
  "      final exitCode = await process.exitCode;",
  "      return ChocoResult(",
  "        success: exitCode == 0,",
  "        output: outputBuf.toString(),",
  "        error: errorBuf.toString(),",
  "        exitCode: exitCode,",
  "      );",
  "    } catch (e) {",
  "      onOutput?.call('Error: $e');",
  "      return ChocoResult(",
  "        success: false,",
  "        output: outputBuf.toString(),",
  "        error: e.toString(),",
  "        exitCode: -1,",
  "      );",
  "    }",
  "  }",
  "",
  "  /// Returns the list of locally installed Chocolatey packages.",
  "  Future<List<PackageModel>> listInstalled() async {",
  "    try {",
  "      final result = await Process.run(",
  "        _powershell,",
  "        ['-NoProfile', '-Command', 'choco list --limit-output'],",
  "        runInShell: false,",
  "      );",
  "      if (result.exitCode != 0) return [];",
  "      return _parseListOutput(result.stdout as String, isInstalled: true);",
  "    } catch (_) {",
  "      return [];",
  "    }",
  "  }",
  "",
  "  /// Searches the Chocolatey community feed for [keyword].",
  "  Future<List<PackageModel>> search(String keyword) async {",
  "    if (keyword.trim().isEmpty) return [];",
  "    try {",
  "      final escaped = keyword.replaceAll(\"'\", \"''\");",
  "      final result = await Process.run(",
  "        _powershell,",
  "        [",
  "          '-NoProfile',",
  "          '-Command',",
  "          \"choco search '\\$escaped' --limit-output\",",
  "        ],",
  "        runInShell: false,",
  "      );",
  "      if (result.exitCode != 0) return [];",
  "      return _parseListOutput(result.stdout as String, isInstalled: false);",
  "    } catch (_) {",
  "      return [];",
  "    }",
  "  }",
  "",
  "  /// Installs [packageName] via `choco install -y`.",
  "  Future<ChocoResult> installPackage(",
  "    String packageName, {",
  "    void Function(String line)? onOutput,",
  "  }) async {",
  "    return _runStreaming(",
  "      \"choco install '\\$packageName' -y --no-progress\",",
  "      onOutput: onOutput,",
  "    );",
  "  }",
  "",
  "  /// Uninstalls [packageName] via `choco uninstall -y`.",
  "  Future<ChocoResult> uninstallPackage(",
  "    String packageName, {",
  "    void Function(String line)? onOutput,",
  "  }) async {",
  "    return _runStreaming(",
  "      \"choco uninstall '\\$packageName' -y --no-progress\",",
  "      onOutput: onOutput,",
  "    );",
  "  }",
  "",
  "  Future<ChocoResult> _runStreaming(",
  "    String command, {",
  "    void Function(String line)? onOutput,",
  "  }) async {",
  "    final outputBuf = StringBuffer();",
  "    final errorBuf = StringBuffer();",
  "    try {",
  "      final process = await Process.start(",
  "        _powershell,",
  "        ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-Command', command],",
  "        runInShell: false,",
  "      );",
  "      process.stdout",
  "          .transform(const Utf8Decoder(allowMalformed: true))",
  "          .transform(const LineSplitter())",
  "          .listen((line) {",
  "        outputBuf.writeln(line);",
  "        onOutput?.call(line);",
  "      });",
  "      process.stderr",
  "          .transform(const Utf8Decoder(allowMalformed: true))",
  "          .transform(const LineSplitter())",
  "          .listen((line) {",
  "        errorBuf.writeln(line);",
  "        onOutput?.call('[ERR] $line');",
  "      });",
  "      final exitCode = await process.exitCode;",
  "      return ChocoResult(",
  "        success: exitCode == 0,",
  "        output: outputBuf.toString(),",
  "        error: errorBuf.toString(),",
  "        exitCode: exitCode,",
  "      );",
  "    } catch (e) {",
  "      onOutput?.call('Error: $e');",
  "      return ChocoResult(",
  "        success: false,",
  "        output: outputBuf.toString(),",
  "        error: e.toString(),",
  "        exitCode: -1,",
  "      );",
  "    }",
  "  }",
  "",
  "  List<PackageModel> _parseListOutput(",
  "    String output, {",
  "    required bool isInstalled,",
  "  }) {",
  "    final packages = <PackageModel>[];",
  "    for (final raw in output.split('\\n')) {",
  "      final line = raw.trim();",
  "      if (line.isEmpty) continue;",
  "      if (RegExp(r'^\\d+ package').hasMatch(line)) continue;",
  "      final parts = line.split('|');",
  "      if (parts.length >= 2) {",
  "        packages.add(PackageModel(",
  "          name: parts[0].trim(),",
  "          version: parts[1].trim(),",
  "          description: parts.length >= 3 ? parts[2].trim() : '',",
  "          isInstalled: isInstalled,",
  "        ));",
  "      }",
  "    }",
  "    return packages;",
  "  }",
  "}",
].join('\n');

fs.writeFileSync(path.join(base, 'services/choco_service.dart'), chocoService, 'utf8');
console.log('Written choco_service.dart: ' + chocoService.split('\n').length + ' lines');

// ---- Verify package_model.dart uses PackageModel ----
const pm = fs.readFileSync(path.join(base, 'models/package_model.dart'), 'utf8');
console.log('package_model.dart has PackageModel: ' + pm.includes('class PackageModel'));

// ---- Verify app_provider.dart uses PackageModel ----
const ap = fs.readFileSync(path.join(base, 'providers/app_provider.dart'), 'utf8');
console.log('app_provider.dart has PackageModel: ' + ap.includes('PackageModel'));
console.log('app_provider.dart has ChocolateyPackage: ' + ap.includes('ChocolateyPackage'));
